### PR TITLE
Fixed the issue of process not exiting when window is closed

### LINKED ISSUE #5: Fix process exit issue

### PR DESCRIPTION
**Pull request by NethmiRodrigo**
Fixes #5

### CODE REVIEW

**Review by shalithasuranga — APPROVED** [review]
Thanks for sending this PR. All good, but could you please use the original formatting (I guess it's a four-space indentation)? We are going to create a in-depth document for JavaScript/C++ code styling, but please update it manually this time ;)

**Comment by NethmiRodrigo** [comment]
> Thanks for sending this PR. All good, but could you please use the original formatting (I guess it's a four-space indentation)? We are going to create a in-depth document for JavaScript/C++ code styling, but please update it manually this time ;)

Will do! Sorry that was prettier doing that😅

**Comment by shalithasuranga** [comment]
Hey.. seems like now we have some Git conflicts. If you could update the code style and fix conflicting files, we can merge this PR :tada: Thanks :)

**Comment by NethmiRodrigo** [comment]
> Hey.. seems like now we have some Git conflicts. If you could update the code style and fix conflicting files, we can merge this PR 🎉 Thanks :)

Hi! Sorry about the delay. Fixed the conflicts and the indentation issue. Hope its alright now :)

**Comment by shalithasuranga** [comment]
Hey.. thanks for the update. could you please double-check and match the existing code style? I think you can checkout to the original version and add only the specific line without auto-formatting ;)

**Comment by NethmiRodrigo** [comment]
> Hey.. thanks for the update. could you please double-check and match the existing code style? I think you can checkout to the original version and add only the specific line without auto-formatting ;)

Sorry about that. I took it now from the original version and added only the specific line. Will turn prettier off next time😅

**Review by shalithasuranga — APPROVED** [review]
Looks great.. Thanks :tada:

**Pull request merged**
